#:schema node_modules/wrangler/config-schema.json
name = "cf-test-web"
compatibility_date = "2026-08-09"

# ★公開するReactの出力フォルダを明示します
[assets]
directory = "./dist"

# ★本番DBをコード側から100%強制接続させる設定です
[[d1_databases]]
binding = "DB"
database_name = "my-production-db"
database_id = "あなたの本番用D1データベースのID"
